CREATE TABLE IF NOT EXISTS CUSTFILE (
    CUSTOMER_ID VARCHAR(10) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(30),
    CUSTOMER_PHONE VARCHAR(15),
    CUSTOMER_ADDRESS VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS AGS_BANK_CODE (
    BANK_CODE VARCHAR(12) PRIMARY KEY,
    BANK_NAME VARCHAR(60),
    BANK_STATUS VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS AGS_BATCH_CTL (
    BATCH_DATE VARCHAR(8) PRIMARY KEY,
    BATCH_ID VARCHAR(32),
    BATCH_STATUS VARCHAR(1),
    START_TS VARCHAR(26),
    END_TS VARCHAR(26),
    UPDATE_TS VARCHAR(26)
);

CREATE TABLE IF NOT EXISTS AGS_DAILY_NETTING (
    BATCH_DATE VARCHAR(8),
    CLEAR_CHANNEL VARCHAR(4),
    COUNTER_BANK VARCHAR(12),
    CURRENCY VARCHAR(3),
    OUT_COUNT VARCHAR(18),
    IN_COUNT VARCHAR(18),
    OUT_AMOUNT VARCHAR(32),
    IN_AMOUNT VARCHAR(32),
    NET_AMOUNT VARCHAR(32),
    CREATE_TS VARCHAR(26)
);

CREATE TABLE IF NOT EXISTS AGS_INWARD_PAY (
    IN_MSG_ID VARCHAR(32),
    IN_SEQ VARCHAR(18),
    SENDER_BANK VARCHAR(12),
    RECEIVER_BANK VARCHAR(12),
    PAYER_ACCT VARCHAR(32),
    PAYER_NAME VARCHAR(60),
    PAYEE_ACCT VARCHAR(32),
    PAYEE_NAME VARCHAR(60),
    CLEAR_CHANNEL VARCHAR(4),
    CURRENCY VARCHAR(3),
    AMOUNT VARCHAR(32),
    NET_AMOUNT VARCHAR(32),
    IN_DATE VARCHAR(8),
    POST_FLAG VARCHAR(1),
    RETURN_REASON VARCHAR(80),
    STATUS VARCHAR(1),
    CREATE_TS VARCHAR(26),
    UPDATE_TS VARCHAR(26)
);

CREATE TABLE IF NOT EXISTS AGS_OUTWARD_PAY (
    PAY_SEQ VARCHAR(24),
    CLEAR_SEQ VARCHAR(18),
    PAYER_ACCT VARCHAR(32),
    PAYER_NAME VARCHAR(60),
    PAYER_BANK VARCHAR(12),
    PAYEE_ACCT VARCHAR(32),
    PAYEE_NAME VARCHAR(60),
    PAYEE_BANK VARCHAR(12),
    CLEAR_CHANNEL VARCHAR(4),
    CURRENCY VARCHAR(3),
    AMOUNT VARCHAR(32),
    NET_AMOUNT VARCHAR(32),
    URGENT_FLAG VARCHAR(1),
    PURPOSE_CODE VARCHAR(8),
    REMARK VARCHAR(120),
    TXN_DATE VARCHAR(8),
    STATUS VARCHAR(1),
    CREATE_TS VARCHAR(26),
    UPDATE_TS VARCHAR(26)
);

CREATE TABLE IF NOT EXISTS AGS_SETTLE_POSITION (
    CLEAR_DATE VARCHAR(8),
    CLEAR_CHANNEL VARCHAR(4),
    COUNTER_BANK VARCHAR(12),
    CURRENCY VARCHAR(3),
    NET_AMOUNT VARCHAR(32),
    OUT_COUNT VARCHAR(18),
    OUT_AMOUNT VARCHAR(32),
    LAST_CLEAR_SEQ VARCHAR(18),
    IN_COUNT VARCHAR(18),
    IN_AMOUNT VARCHAR(32),
    LAST_IN_SEQ VARCHAR(18),
    UPDATE_TS VARCHAR(26)
);
